#!/usr/bin/env node
/**
 * Secondary-page shell sync: stamps the canonical header and the environmental-field layers into every
 * secondary marketing page and into the isolated Demo Lab, and generates the demo's copies of the shared
 * stylesheet and field renderer. The homepage (index.html) is the source of the header's design; this
 * script keeps the other pages from drifting away from it.
 *
 *   node scripts/shell/sync-shell.mjs          write the stamped pages and generated files
 *   node scripts/shell/sync-shell.mjs --check  exit 1 if any page or generated file differs (CI guard)
 *
 * Pages carry two marker pairs:
 *   <!-- shell:header --> ... <!-- /shell:header -->   the canonical header markup
 *   <!-- shell:field -->  ... <!-- /shell:field -->    the fixed field canvas and its veil
 *
 * The demo deploys from demo/ alone (demo/netlify.toml, Package directory "demo"), so it cannot reach
 * css/ or js/ of the marketing root. Its copies are GENERATED here from the canonical sources:
 *   demo/styles/shell.css        = css/style.css with every @import inlined into its cascade layer
 *   demo/scripts/shell/*.js      = js/experience/{scroll,field,shell}.js verbatim
 * Never edit those copies by hand; edit the canonical files and re-run this script.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const CHECK = process.argv.includes('--check');

const MARKETING_PAGES = [
    // capability / service pages linked from the homepage Yetenekler dropdown and footer
    { file: 'pages/rpa.html', active: 'yetenekler' },
    { file: 'pages/webscraping.html', active: 'yetenekler' },
    { file: 'pages/api.html', active: 'yetenekler' },
    { file: 'pages/ai-assistant.html', active: 'yetenekler' },
    { file: 'pages/financial-indicators.html', active: 'yetenekler' },
    { file: 'pages/training-consulting.html', active: 'yetenekler' },
    { file: 'pages/investment-analytics.html', active: 'yetenekler' },
    // legal pages linked from the homepage footer
    { file: 'pages/kvkk.html', active: null },
    { file: 'pages/gizlilik.html', active: null },
    { file: 'pages/kullanim-sartlari.html', active: null },
    { file: 'pages/hizmet-sozlesmesi.html', active: null },
];
const DEMO_PAGE = { file: 'demo/index.html', active: 'demo' };

const FIELD_MARKUP = `<canvas class="field" data-field data-field-mode="hero" aria-hidden="true"></canvas>
<div class="field-veil" aria-hidden="true"></div>`;

const read = (rel) => fs.readFile(path.join(ROOT, rel), 'utf8');
const normalize = (s) => s.replace(/\r\n/g, '\n');

function renderHeader(template, { origin, active }) {
    // marketing pages use root-relative destinations (same origin, work on the local preview too);
    // the demo lives on demo.teknoify.com and must point at the canonical marketing origin
    const home = origin === 'demo' ? 'https://teknoify.com/' : '/';
    const pages = origin === 'demo' ? 'https://teknoify.com/pages/' : '/pages/';
    return template
        .replace(/\{\{home\}\}/g, home)
        .replace(/\{\{pages\}\}/g, pages)
        .replace(/\{\{active_yetenekler\}\}/g, active === 'yetenekler' ? ' is-active' : '')
        .replace(/\{\{active_demo\}\}/g, active === 'demo' ? ' aria-current="page"' : '');
}

function stamp(html, name, content) {
    const open = `<!-- shell:${name} -->`, close = `<!-- /shell:${name} -->`;
    const a = html.indexOf(open), b = html.indexOf(close);
    if (a < 0 || b < 0 || b < a) throw new Error(`missing ${open} … ${close} markers`);
    return html.slice(0, a + open.length) + '\n' + content.trim() + '\n' + html.slice(b);
}

/** css/style.css with every layered @import inlined into an @layer block, so one file carries the system */
async function flattenStylesheet() {
    const src = normalize(await read('css/style.css'));
    const lines = src.split('\n');
    const out = ['/* GENERATED by scripts/shell/sync-shell.mjs from css/style.css and its imports. Do not edit; edit the canonical files. */'];
    for (const line of lines) {
        const m = line.match(/^@import url\("\.\/([^"?]+)(?:\?[^"]*)?"\) layer\((\w+)\);/);
        if (!m) { out.push(line); continue; }
        const body = normalize(await read(path.posix.join('css', m[1]))).trim();
        out.push(`@layer ${m[2]} {\n/* ---- ${m[1]} ---- */\n${body}\n}`);
    }
    return out.join('\n') + '\n';
}

async function generatedDemoFiles() {
    const files = new Map();
    files.set('demo/styles/shell.css', await flattenStylesheet());
    for (const name of ['scroll.js', 'field.js', 'shell.js']) {
        const body = normalize(await read(`js/experience/${name}`));
        files.set(`demo/scripts/shell/${name}`, `/* GENERATED copy of js/experience/${name} (scripts/shell/sync-shell.mjs). Do not edit here. */\n${body}`);
    }
    return files;
}

async function main() {
    const template = normalize(await read('scripts/shell/header.template.html'));
    const drift = [];
    const writes = [];
    const pages = [...MARKETING_PAGES.map((p) => ({ ...p, origin: 'marketing' })), { ...DEMO_PAGE, origin: 'demo' }];
    for (const page of pages) {
        const current = await read(page.file);
        let next = normalize(current);
        next = stamp(next, 'header', renderHeader(template, page));
        next = stamp(next, 'field', FIELD_MARKUP);
        if (next !== normalize(current)) { drift.push(page.file); writes.push([page.file, next]); }
    }
    for (const [rel, content] of await generatedDemoFiles()) {
        let current = null;
        try { current = normalize(await read(rel)); } catch { current = null; }
        if (current !== content) { drift.push(rel); writes.push([rel, content]); }
    }
    if (CHECK) {
        if (drift.length) { console.error('shell out of sync:\n  ' + drift.join('\n  ') + '\nrun: node scripts/shell/sync-shell.mjs'); process.exit(1); }
        console.log(`shell in sync (${pages.length} pages, demo copies current)`);
        return;
    }
    for (const [rel, content] of writes) {
        await fs.mkdir(path.dirname(path.join(ROOT, rel)), { recursive: true });
        await fs.writeFile(path.join(ROOT, rel), content, 'utf8');
    }
    console.log(writes.length ? `shell written:\n  ${writes.map(([r]) => r).join('\n  ')}` : 'shell already in sync');
}

main().catch((e) => { console.error(e.message); process.exit(1); });
