/* global AbortController, ApexCharts, WebSocket, ResizeObserver */
import { auth, db } from "/js/lib/firebase.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/9.23.0/firebase-auth.js";
import { doc, getDoc } from "https://www.gstatic.com/firebasejs/9.23.0/firebase-firestore.js";

const REST_BASE="https://data-api.binance.vision", WS_BASE="wss://stream.binance.com:9443/ws", LIMIT=300, FAVORITES_KEY="teknoify_investment_favorites_v1";
const ASSETS=[
 {symbol:"BTCUSDT",display:"BTC-USDT",name:"Bitcoin",tr:"Bitcoin",icon:"B",seed:64000},{symbol:"ETHUSDT",display:"ETH-USDT",name:"Ethereum",tr:"Ethereum",icon:"E",seed:3200},{symbol:"BNBUSDT",display:"BNB-USDT",name:"BNB",tr:"BNB",icon:"N",seed:580},{symbol:"SOLUSDT",display:"SOL-USDT",name:"Solana",tr:"Solana",icon:"S",seed:145},{symbol:"XRPUSDT",display:"XRP-USDT",name:"XRP",tr:"XRP",icon:"X",seed:.58},{symbol:"ADAUSDT",display:"ADA-USDT",name:"Cardano",tr:"Cardano",icon:"A",seed:.42},{symbol:"AVAXUSDT",display:"AVAX-USDT",name:"Avalanche",tr:"Avalanche",icon:"V",seed:28},{symbol:"DOGEUSDT",display:"DOGE-USDT",name:"Dogecoin",tr:"Dogecoin",icon:"D",seed:.12}
];
const state={selected:ASSETS[0],interval:"1h",candles:[],priceChart:null,volumeChart:null,ws:null,generation:0,retries:0,reconnectTimer:null,pollTimer:null,watchTimer:null,watchInFlight:false,watchBackoff:30000,favorites:new Set(),filter:"all",query:"",hidden:false,unloading:false};
const $=id=>document.getElementById(id);
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:2});
const smallMoney=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:4,maximumFractionDigits:6});
const pctFmt=new Intl.NumberFormat("en-US",{minimumFractionDigits:2,maximumFractionDigits:2,signDisplay:"always"});
const trTime=new Intl.DateTimeFormat("tr-TR",{timeZone:"Europe/Istanbul",dateStyle:"short",timeStyle:"short"});
function safeNum(v){const n=Number(v);return Number.isFinite(n)?n:null} function fmtPrice(n){return Number.isFinite(n)?(Math.abs(n)<1?smallMoney:money).format(n):"—"} function fmtPct(n){return Number.isFinite(n)?`${pctFmt.format(n)}%`:"—"} function changeClass(n){return n>0?"positive":n<0?"negative":"neutral"}
function setText(id,v){const el=$(id); if(el) el.textContent=v} function setStatus(kind,text){const el=$("market-status"); if(!el)return; el.className=`market-status ${kind}`; el.replaceChildren(document.createElement("span"),document.createTextNode(text));}
function loadFavs(){try{state.favorites=new Set(JSON.parse(localStorage.getItem(FAVORITES_KEY)||"[]").filter(s=>ASSETS.some(a=>a.symbol===s)))}catch{state.favorites=new Set()}} function saveFavs(){localStorage.setItem(FAVORITES_KEY,JSON.stringify([...state.favorites]))}
async function authInit(){onAuthStateChanged(auth,async user=>{if(!user){location.href="/";return} let userData={}; try{const s=await getDoc(doc(db,"users",user.uid)); if(s.exists()){const rootData=s.data()||{}; userData=rootData.data||rootData||{}}}catch(e){console.warn("Profil okunamadı",e)} const name=userData.displayName||userData.name||user.displayName||user.email||"Teknoify Kullanıcısı"; const photo=userData.profile?.photoURL||userData.photoURL||user.photoURL||""; window.USER_SESSION={uid:user.uid,email:user.email,displayName:name,photoURL:photo,isAdmin:!!userData.isAdmin}; renderProfile(name,photo); if(typeof window.TK_RENDER_SIDEBAR==="function") window.TK_RENDER_SIDEBAR(); startMarket();});}
function renderProfile(name,photo){setText("investment-user-name",name); const av=$("investment-user-avatar"); if(!av)return; av.textContent=""; if(photo){const img=document.createElement("img"); img.src=photo; img.alt=""; av.appendChild(img)}else av.textContent=(name.trim()[0]||"T").toUpperCase(); $("investment-profile-button")?.addEventListener("click",()=>document.querySelector(".user-profile,.profile-trigger")?.click());}
function candleFromRow(r){if(!Array.isArray(r)||r.length<6)return null; const c={timestamp:safeNum(r[0]),open:safeNum(r[1]),high:safeNum(r[2]),low:safeNum(r[3]),close:safeNum(r[4]),volume:safeNum(r[5])}; return [c.timestamp,c.open,c.high,c.low,c.close,c.volume].every(Number.isFinite)?c:null}
function normalize(rows){const map=new Map(); rows.map(candleFromRow).filter(Boolean).forEach(c=>map.set(c.timestamp,c)); return [...map.values()].sort((a,b)=>a.timestamp-b.timestamp).slice(-LIMIT)}
async function fetchCandles(symbol=state.selected.symbol,interval=state.interval){const ctl=new AbortController(); const t=setTimeout(()=>ctl.abort(),10000); try{const url=`${REST_BASE}/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=${encodeURIComponent(interval)}&limit=${LIMIT}`; const res=await fetch(url,{signal:ctl.signal}); if(!res.ok) throw new Error(`Kline HTTP ${res.status}`); const json=await res.json(); if(!Array.isArray(json)) throw new Error("Malformed kline payload"); const candles=normalize(json); if(!candles.length) throw new Error("Empty kline data"); return candles}finally{clearTimeout(t)}}
function smaData(){return state.candles.map((c,i)=>{if(i<19)return {x:c.timestamp,y:null}; const avg=state.candles.slice(i-19,i+1).reduce((s,v)=>s+v.close,0)/20; return {x:c.timestamp,y:Number(avg.toFixed(8))}})}
function priceSeries(){return [{name:"Fiyat",type:"candlestick",data:state.candles.map(c=>({x:c.timestamp,y:[c.open,c.high,c.low,c.close]}))},{name:"SMA 20",type:"line",data:smaData()}]} function volumeSeries(){return [{name:"Hacim",data:state.candles.map(c=>({x:c.timestamp,y:c.volume,fillColor:c.close>=c.open?"#10b981":"#ef4444"}))}]}
function chartOpts(){return {chart:{id:"investment-price-chart",type:"candlestick",height:430,background:"transparent",animations:{enabled:false},toolbar:{show:false},zoom:{enabled:true}},theme:{mode:"dark"},grid:{borderColor:"rgba(255,255,255,.055)"},xaxis:{type:"datetime",labels:{style:{colors:"#a1a1aa"},datetimeUTC:false,formatter:v=>trTime.format(new Date(v))}},yaxis:{opposite:true,labels:{style:{colors:"#a1a1aa"},formatter:v=>fmtPrice(v)}},tooltip:{theme:"dark",x:{formatter:v=>trTime.format(new Date(v))}},plotOptions:{candlestick:{colors:{upward:"#10b981",downward:"#ef4444"}}},stroke:{width:[1,2],colors:[undefined,"#f59e0b"]},series:priceSeries()}}
function volOpts(){return {chart:{id:"investment-volume-chart",type:"bar",height:140,background:"transparent",animations:{enabled:false},toolbar:{show:false},zoom:{enabled:false}},theme:{mode:"dark"},grid:{borderColor:"rgba(255,255,255,.055)"},plotOptions:{bar:{columnWidth:"70%"}},xaxis:{type:"datetime",labels:{show:false}},yaxis:{labels:{style:{colors:"#a1a1aa"},formatter:v=>Intl.NumberFormat("en-US",{notation:"compact"}).format(v)}},tooltip:{theme:"dark",x:{formatter:v=>trTime.format(new Date(v))}},series:volumeSeries()}}
async function renderCharts(){if(!state.priceChart){state.priceChart=new ApexCharts($("investment-price-chart"),chartOpts()); state.volumeChart=new ApexCharts($("investment-volume-chart"),volOpts()); await Promise.all([state.priceChart.render(),state.volumeChart.render()])}else{await state.priceChart.updateSeries(priceSeries(),false); await state.volumeChart.updateSeries(volumeSeries(),false)} $("price-chart-card")?.classList.remove("loading"); $("volume-chart-card")?.classList.remove("loading");}
function updateSelected(price,change){setText("selected-display-symbol",state.selected.display); setText("selected-asset-name",state.selected.name); setText("selected-asset-icon",state.selected.icon); setText("selected-current-price",fmtPrice(price)); const el=$("selected-change"); if(el){el.textContent=fmtPct(change); el.className=`change-value ${changeClass(change)}`; el.setAttribute("aria-label",`24 saatlik değişim ${fmtPct(change)}`)} document.title=`${state.selected.display} | Yatırım | Teknoify`;}
async function loadSymbol(){state.generation++; const gen=state.generation; closeSocket(false); clearPolling(); setStatus("connecting","Bağlanıyor"); $("chart-message").hidden=true; $("price-chart-card")?.classList.add("loading"); $("volume-chart-card")?.classList.add("loading"); updateSelected(NaN,NaN); try{state.candles=await fetchCandles(); if(gen!==state.generation)return; await renderCharts(); updateSelected(state.candles.at(-1)?.close, getWatchChange(state.selected.symbol)); openSocket(gen)}catch(e){console.error("Kline yüklenemedi",e); $("chart-message").hidden=false; tryDemo();}}
function openSocket(gen=state.generation){if(state.hidden||state.unloading)return; closeSocket(false); const ws=new WebSocket(`${WS_BASE}/${state.selected.symbol.toLowerCase()}@kline_${state.interval}`); state.ws=ws; ws.onopen=()=>{if(gen!==state.generation)return; state.retries=0; setStatus("live","Canlı")}; ws.onmessage=ev=>{if(gen!==state.generation)return; try{const msg=JSON.parse(ev.data); const k=msg.k; if(!k||k.s!==state.selected.symbol||k.i!==state.interval)return; const c={timestamp:safeNum(k.t),open:safeNum(k.o),high:safeNum(k.h),low:safeNum(k.l),close:safeNum(k.c),volume:safeNum(k.v)}; if(![c.timestamp,c.open,c.high,c.low,c.close,c.volume].every(Number.isFinite))return; upsertCandle(c); updateSelected(c.close,getWatchChange(state.selected.symbol)); renderCharts()}catch(e){console.warn("WS mesajı işlenemedi",e)}}; ws.onerror=()=>setStatus("connecting","Bağlanıyor"); ws.onclose=()=>{if(gen!==state.generation||state.unloading)return; scheduleReconnect(gen)}}
function upsertCandle(c){const i=state.candles.findIndex(x=>x.timestamp===c.timestamp); if(i>=0)state.candles[i]=c; else state.candles.push(c); state.candles.sort((a,b)=>a.timestamp-b.timestamp); state.candles=state.candles.slice(-LIMIT)}
function closeSocket(increment=true){if(increment)state.generation++; if(state.ws){state.ws.onclose=null; state.ws.close(); state.ws=null} if(state.reconnectTimer){clearTimeout(state.reconnectTimer); state.reconnectTimer=null}}
function scheduleReconnect(gen){if(state.reconnectTimer)return; state.retries++; if(state.retries>5){startPolling();return} setStatus("connecting","Bağlanıyor"); const delay=Math.min(30000,1000*2**(state.retries-1)); state.reconnectTimer=setTimeout(()=>{state.reconnectTimer=null; openSocket(gen)},delay)}
function startPolling(){clearPolling(); setStatus("delayed","Gecikmeli"); state.pollTimer=setInterval(async()=>{if(state.hidden)return; try{state.candles=await fetchCandles(); await renderCharts(); updateSelected(state.candles.at(-1)?.close,getWatchChange(state.selected.symbol))}catch(e){console.warn("Polling başarısız",e); tryDemo()}},12000)} function clearPolling(){if(state.pollTimer)clearInterval(state.pollTimer); state.pollTimer=null}
function seeded(seed){let x=seed; return()=>((x=(x*9301+49297)%233280)/233280)} function demoCandles(){const rnd=seeded(state.selected.symbol.split("").reduce((s,c)=>s+c.charCodeAt(0),0)); const step={"15m":9e5,"1h":36e5,"4h":144e5,"1d":864e5}[state.interval]; let price=state.selected.seed, now=Date.now()-LIMIT*step; return Array.from({length:LIMIT},(_,i)=>{const open=price; price=Math.max(.0001,price*(1+(rnd()-.5)/35)); const close=price, high=Math.max(open,close)*(1+rnd()/90), low=Math.min(open,close)*(1-rnd()/90); return {timestamp:now+i*step,open,high,low,close,volume:1000+rnd()*10000}})} async function tryDemo(){state.candles=demoCandles(); setStatus("demo","Demo Veri"); const msg=$("chart-message"); msg.hidden=false; msg.querySelector("span").textContent="Canlı piyasa verisine ulaşılamadığı için örnek veriler gösteriliyor."; await renderCharts(); updateSelected(state.candles.at(-1).close,NaN)}
const watchData=new Map(); function getWatchChange(s){return watchData.get(s)?.change}
function renderWatchlist(){const rows=$("watchlist-rows"); rows.textContent=""; const q=state.query.trim().toLowerCase(); let items=ASSETS.filter(a=>(state.filter==="all"||state.favorites.has(a.symbol))&&(!q||[a.display,a.symbol,a.name,a.tr].some(v=>v.toLowerCase().includes(q)))); if(!items.length){const p=document.createElement("p"); p.className="empty-state"; p.textContent=state.filter==="favorites"&&!state.favorites.size?"Henüz favori varlığınız yok.":"Sonuç bulunamadı."; rows.appendChild(p); return} items.forEach(a=>{const row=document.createElement("button"); row.type="button"; row.className="watch-row"; row.dataset.symbol=a.symbol; row.setAttribute("aria-current",String(a.symbol===state.selected.symbol)); row.innerHTML=`<span class="asset-token"></span><span><strong></strong><span class="watch-symbol"></span></span><span class="watch-price"><strong></strong><span></span></span>`; row.children[0].textContent=a.icon; row.children[1].querySelector("strong").textContent=a.name; row.children[1].querySelector(".watch-symbol").textContent=a.display; const d=watchData.get(a.symbol)||{}; row.children[2].querySelector("strong").textContent=fmtPrice(d.price); const ch=row.children[2].querySelector("span"); ch.textContent=fmtPct(d.change); ch.className=changeClass(d.change); const fav=document.createElement("button"); fav.type="button"; fav.className=`favorite-button ${state.favorites.has(a.symbol)?"is-favorite":""}`; fav.setAttribute("aria-label",`${a.display} favorisini ${state.favorites.has(a.symbol)?"kaldır":"ekle"}`); fav.innerHTML='<i class="fas fa-star"></i>'; fav.onclick=e=>{e.stopPropagation(); state.favorites.has(a.symbol)?state.favorites.delete(a.symbol):state.favorites.add(a.symbol); saveFavs(); renderWatchlist()}; row.appendChild(fav); row.onclick=()=>{state.selected=a; renderWatchlist(); loadSymbol()}; rows.appendChild(row)})}
async function updateWatchlist(){if(state.watchInFlight||state.hidden)return; state.watchInFlight=true; const err=$("watchlist-error"); try{const symbols=encodeURIComponent(JSON.stringify(ASSETS.map(a=>a.symbol))); const res=await fetch(`${REST_BASE}/api/v3/ticker/24hr?symbols=${symbols}`); if(res.status===429){state.watchBackoff=Math.min(state.watchBackoff*2,240000); throw new Error("Rate limited")} if(!res.ok)throw new Error(`Ticker HTTP ${res.status}`); const json=await res.json(); if(!Array.isArray(json))throw new Error("Malformed ticker"); json.forEach(t=>{const a=ASSETS.find(x=>x.symbol===t.symbol); const price=safeNum(t.lastPrice), change=safeNum(t.priceChangePercent); if(a&&Number.isFinite(price)&&Number.isFinite(change))watchData.set(a.symbol,{price,change})}); state.watchBackoff=30000; err.hidden=true; setText("watchlist-updated",trTime.format(new Date())); updateSelected(watchData.get(state.selected.symbol)?.price??state.candles.at(-1)?.close,getWatchChange(state.selected.symbol)); renderWatchlist()}catch(e){console.warn("Watchlist güncellenemedi",e); err.hidden=false}finally{state.watchInFlight=false; scheduleWatchlist()}}
function scheduleWatchlist(){clearTimeout(state.watchTimer); state.watchTimer=setTimeout(updateWatchlist,state.watchBackoff)}
function bind(){loadFavs(); renderWatchlist(); $("watchlist-search").addEventListener("input",e=>{state.query=e.target.value; renderWatchlist()}); document.querySelectorAll(".watchlist-filters button").forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter; document.querySelectorAll(".watchlist-filters button").forEach(x=>x.classList.toggle("active",x===b)); renderWatchlist()}); document.querySelectorAll(".interval-controls button").forEach(b=>{b.setAttribute("aria-pressed",String(b.classList.contains("active"))); b.onclick=()=>{if(state.interval===b.dataset.interval)return; state.interval=b.dataset.interval; document.querySelectorAll(".interval-controls button").forEach(x=>{x.classList.toggle("active",x===b); x.setAttribute("aria-pressed",String(x===b))}); loadSymbol()}}); document.querySelectorAll(".tool-button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tool-button").forEach(x=>x.classList.toggle("active",x===b)); if(b.dataset.tool==="zoom-in")state.priceChart?.zoomX(Date.now()-7*864e5,Date.now()); if(b.dataset.tool==="zoom-out"||b.dataset.tool==="reset")state.priceChart?.resetSeries();}); $("retry-market-load").onclick=loadSymbol; const ro=new ResizeObserver(()=>{state.priceChart?.resize(); state.volumeChart?.resize()}); ro.observe(document.querySelector(".investment-terminal")); window.addEventListener("pagehide",cleanup); window.addEventListener("beforeunload",cleanup); document.addEventListener("visibilitychange",()=>{state.hidden=document.hidden; if(state.hidden){closeSocket(); clearPolling(); clearTimeout(state.watchTimer)}else{loadSymbol(); scheduleWatchlist()}}); window.addEventListener("unload",()=>ro.disconnect())}
function cleanup(){state.unloading=true; closeSocket(); clearPolling(); clearTimeout(state.watchTimer); state.priceChart?.destroy(); state.volumeChart?.destroy()}
function startMarket(){bind(); updateSelected(NaN,NaN); loadSymbol(); updateWatchlist()}
authInit();
